/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CategoryDto', 'model/CustomerDto', 'model/MovementDetailDto', 'model/MovementDto', 'model/MovementTypeDto', 'model/ProductDto', 'model/ProductRepositoryDto', 'model/RepositoryDto', 'model/ResponseCanonicalCategoryDto', 'model/ResponseCanonicalCustomerDto', 'model/ResponseCanonicalListCategoryDto', 'model/ResponseCanonicalListCustomerDto', 'model/ResponseCanonicalListMovementDetailDto', 'model/ResponseCanonicalListMovementDto', 'model/ResponseCanonicalListMovementTypeDto', 'model/ResponseCanonicalListProductDto', 'model/ResponseCanonicalListProductRepositoryDto', 'model/ResponseCanonicalListRepositoryDto', 'model/ResponseCanonicalListSupplierDto', 'model/ResponseCanonicalMovementDetailDto', 'model/ResponseCanonicalMovementDto', 'model/ResponseCanonicalMovementTypeDto', 'model/ResponseCanonicalProductDto', 'model/ResponseCanonicalProductRepositoryDto', 'model/ResponseCanonicalRepositoryDto', 'model/ResponseCanonicalSupplierDto', 'model/ResponseCanonicalstring', 'model/SupplierDto', 'api/CategoryControllerApi', 'api/CustomerControllerApi', 'api/MovementControllerApi', 'api/MovementDetailControllerApi', 'api/MovementTypeControllerApi', 'api/ProductControllerApi', 'api/ProductRepositoryControllerApi', 'api/RepositoryControllerApi', 'api/RootControllerApi', 'api/SupplierControllerApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CategoryDto'), require('./model/CustomerDto'), require('./model/MovementDetailDto'), require('./model/MovementDto'), require('./model/MovementTypeDto'), require('./model/ProductDto'), require('./model/ProductRepositoryDto'), require('./model/RepositoryDto'), require('./model/ResponseCanonicalCategoryDto'), require('./model/ResponseCanonicalCustomerDto'), require('./model/ResponseCanonicalListCategoryDto'), require('./model/ResponseCanonicalListCustomerDto'), require('./model/ResponseCanonicalListMovementDetailDto'), require('./model/ResponseCanonicalListMovementDto'), require('./model/ResponseCanonicalListMovementTypeDto'), require('./model/ResponseCanonicalListProductDto'), require('./model/ResponseCanonicalListProductRepositoryDto'), require('./model/ResponseCanonicalListRepositoryDto'), require('./model/ResponseCanonicalListSupplierDto'), require('./model/ResponseCanonicalMovementDetailDto'), require('./model/ResponseCanonicalMovementDto'), require('./model/ResponseCanonicalMovementTypeDto'), require('./model/ResponseCanonicalProductDto'), require('./model/ResponseCanonicalProductRepositoryDto'), require('./model/ResponseCanonicalRepositoryDto'), require('./model/ResponseCanonicalSupplierDto'), require('./model/ResponseCanonicalstring'), require('./model/SupplierDto'), require('./api/CategoryControllerApi'), require('./api/CustomerControllerApi'), require('./api/MovementControllerApi'), require('./api/MovementDetailControllerApi'), require('./api/MovementTypeControllerApi'), require('./api/ProductControllerApi'), require('./api/ProductRepositoryControllerApi'), require('./api/RepositoryControllerApi'), require('./api/RootControllerApi'), require('./api/SupplierControllerApi'));
  }
}(function(ApiClient, CategoryDto, CustomerDto, MovementDetailDto, MovementDto, MovementTypeDto, ProductDto, ProductRepositoryDto, RepositoryDto, ResponseCanonicalCategoryDto, ResponseCanonicalCustomerDto, ResponseCanonicalListCategoryDto, ResponseCanonicalListCustomerDto, ResponseCanonicalListMovementDetailDto, ResponseCanonicalListMovementDto, ResponseCanonicalListMovementTypeDto, ResponseCanonicalListProductDto, ResponseCanonicalListProductRepositoryDto, ResponseCanonicalListRepositoryDto, ResponseCanonicalListSupplierDto, ResponseCanonicalMovementDetailDto, ResponseCanonicalMovementDto, ResponseCanonicalMovementTypeDto, ResponseCanonicalProductDto, ResponseCanonicalProductRepositoryDto, ResponseCanonicalRepositoryDto, ResponseCanonicalSupplierDto, ResponseCanonicalstring, SupplierDto, CategoryControllerApi, CustomerControllerApi, MovementControllerApi, MovementDetailControllerApi, MovementTypeControllerApi, ProductControllerApi, ProductRepositoryControllerApi, RepositoryControllerApi, RootControllerApi, SupplierControllerApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var InventoryManagementSystem = require('index'); // See note below*.
   * var xxxSvc = new InventoryManagementSystem.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new InventoryManagementSystem.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new InventoryManagementSystem.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new InventoryManagementSystem.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CategoryDto model constructor.
     * @property {module:model/CategoryDto}
     */
    CategoryDto: CategoryDto,
    /**
     * The CustomerDto model constructor.
     * @property {module:model/CustomerDto}
     */
    CustomerDto: CustomerDto,
    /**
     * The MovementDetailDto model constructor.
     * @property {module:model/MovementDetailDto}
     */
    MovementDetailDto: MovementDetailDto,
    /**
     * The MovementDto model constructor.
     * @property {module:model/MovementDto}
     */
    MovementDto: MovementDto,
    /**
     * The MovementTypeDto model constructor.
     * @property {module:model/MovementTypeDto}
     */
    MovementTypeDto: MovementTypeDto,
    /**
     * The ProductDto model constructor.
     * @property {module:model/ProductDto}
     */
    ProductDto: ProductDto,
    /**
     * The ProductRepositoryDto model constructor.
     * @property {module:model/ProductRepositoryDto}
     */
    ProductRepositoryDto: ProductRepositoryDto,
    /**
     * The RepositoryDto model constructor.
     * @property {module:model/RepositoryDto}
     */
    RepositoryDto: RepositoryDto,
    /**
     * The ResponseCanonicalCategoryDto model constructor.
     * @property {module:model/ResponseCanonicalCategoryDto}
     */
    ResponseCanonicalCategoryDto: ResponseCanonicalCategoryDto,
    /**
     * The ResponseCanonicalCustomerDto model constructor.
     * @property {module:model/ResponseCanonicalCustomerDto}
     */
    ResponseCanonicalCustomerDto: ResponseCanonicalCustomerDto,
    /**
     * The ResponseCanonicalListCategoryDto model constructor.
     * @property {module:model/ResponseCanonicalListCategoryDto}
     */
    ResponseCanonicalListCategoryDto: ResponseCanonicalListCategoryDto,
    /**
     * The ResponseCanonicalListCustomerDto model constructor.
     * @property {module:model/ResponseCanonicalListCustomerDto}
     */
    ResponseCanonicalListCustomerDto: ResponseCanonicalListCustomerDto,
    /**
     * The ResponseCanonicalListMovementDetailDto model constructor.
     * @property {module:model/ResponseCanonicalListMovementDetailDto}
     */
    ResponseCanonicalListMovementDetailDto: ResponseCanonicalListMovementDetailDto,
    /**
     * The ResponseCanonicalListMovementDto model constructor.
     * @property {module:model/ResponseCanonicalListMovementDto}
     */
    ResponseCanonicalListMovementDto: ResponseCanonicalListMovementDto,
    /**
     * The ResponseCanonicalListMovementTypeDto model constructor.
     * @property {module:model/ResponseCanonicalListMovementTypeDto}
     */
    ResponseCanonicalListMovementTypeDto: ResponseCanonicalListMovementTypeDto,
    /**
     * The ResponseCanonicalListProductDto model constructor.
     * @property {module:model/ResponseCanonicalListProductDto}
     */
    ResponseCanonicalListProductDto: ResponseCanonicalListProductDto,
    /**
     * The ResponseCanonicalListProductRepositoryDto model constructor.
     * @property {module:model/ResponseCanonicalListProductRepositoryDto}
     */
    ResponseCanonicalListProductRepositoryDto: ResponseCanonicalListProductRepositoryDto,
    /**
     * The ResponseCanonicalListRepositoryDto model constructor.
     * @property {module:model/ResponseCanonicalListRepositoryDto}
     */
    ResponseCanonicalListRepositoryDto: ResponseCanonicalListRepositoryDto,
    /**
     * The ResponseCanonicalListSupplierDto model constructor.
     * @property {module:model/ResponseCanonicalListSupplierDto}
     */
    ResponseCanonicalListSupplierDto: ResponseCanonicalListSupplierDto,
    /**
     * The ResponseCanonicalMovementDetailDto model constructor.
     * @property {module:model/ResponseCanonicalMovementDetailDto}
     */
    ResponseCanonicalMovementDetailDto: ResponseCanonicalMovementDetailDto,
    /**
     * The ResponseCanonicalMovementDto model constructor.
     * @property {module:model/ResponseCanonicalMovementDto}
     */
    ResponseCanonicalMovementDto: ResponseCanonicalMovementDto,
    /**
     * The ResponseCanonicalMovementTypeDto model constructor.
     * @property {module:model/ResponseCanonicalMovementTypeDto}
     */
    ResponseCanonicalMovementTypeDto: ResponseCanonicalMovementTypeDto,
    /**
     * The ResponseCanonicalProductDto model constructor.
     * @property {module:model/ResponseCanonicalProductDto}
     */
    ResponseCanonicalProductDto: ResponseCanonicalProductDto,
    /**
     * The ResponseCanonicalProductRepositoryDto model constructor.
     * @property {module:model/ResponseCanonicalProductRepositoryDto}
     */
    ResponseCanonicalProductRepositoryDto: ResponseCanonicalProductRepositoryDto,
    /**
     * The ResponseCanonicalRepositoryDto model constructor.
     * @property {module:model/ResponseCanonicalRepositoryDto}
     */
    ResponseCanonicalRepositoryDto: ResponseCanonicalRepositoryDto,
    /**
     * The ResponseCanonicalSupplierDto model constructor.
     * @property {module:model/ResponseCanonicalSupplierDto}
     */
    ResponseCanonicalSupplierDto: ResponseCanonicalSupplierDto,
    /**
     * The ResponseCanonicalstring model constructor.
     * @property {module:model/ResponseCanonicalstring}
     */
    ResponseCanonicalstring: ResponseCanonicalstring,
    /**
     * The SupplierDto model constructor.
     * @property {module:model/SupplierDto}
     */
    SupplierDto: SupplierDto,
    /**
     * The CategoryControllerApi service constructor.
     * @property {module:api/CategoryControllerApi}
     */
    CategoryControllerApi: CategoryControllerApi,
    /**
     * The CustomerControllerApi service constructor.
     * @property {module:api/CustomerControllerApi}
     */
    CustomerControllerApi: CustomerControllerApi,
    /**
     * The MovementControllerApi service constructor.
     * @property {module:api/MovementControllerApi}
     */
    MovementControllerApi: MovementControllerApi,
    /**
     * The MovementDetailControllerApi service constructor.
     * @property {module:api/MovementDetailControllerApi}
     */
    MovementDetailControllerApi: MovementDetailControllerApi,
    /**
     * The MovementTypeControllerApi service constructor.
     * @property {module:api/MovementTypeControllerApi}
     */
    MovementTypeControllerApi: MovementTypeControllerApi,
    /**
     * The ProductControllerApi service constructor.
     * @property {module:api/ProductControllerApi}
     */
    ProductControllerApi: ProductControllerApi,
    /**
     * The ProductRepositoryControllerApi service constructor.
     * @property {module:api/ProductRepositoryControllerApi}
     */
    ProductRepositoryControllerApi: ProductRepositoryControllerApi,
    /**
     * The RepositoryControllerApi service constructor.
     * @property {module:api/RepositoryControllerApi}
     */
    RepositoryControllerApi: RepositoryControllerApi,
    /**
     * The RootControllerApi service constructor.
     * @property {module:api/RootControllerApi}
     */
    RootControllerApi: RootControllerApi,
    /**
     * The SupplierControllerApi service constructor.
     * @property {module:api/SupplierControllerApi}
     */
    SupplierControllerApi: SupplierControllerApi
  };

  return exports;
}));
