/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MovementDto', 'model/RepositoryDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MovementDto'), require('./RepositoryDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.MovementTypeDto = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.MovementDto, root.InventoryManagementSystem.RepositoryDto);
  }
}(this, function(ApiClient, MovementDto, RepositoryDto) {
  'use strict';




  /**
   * The MovementTypeDto model module.
   * @module model/MovementTypeDto
   * @version 2.0
   */

  /**
   * Constructs a new <code>MovementTypeDto</code>.
   * @alias module:model/MovementTypeDto
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>MovementTypeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovementTypeDto} obj Optional instance to populate.
   * @return {module:model/MovementTypeDto} The populated <code>MovementTypeDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('movements')) {
        obj['movements'] = ApiClient.convertToType(data['movements'], [MovementDto]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('parentMovementRequired')) {
        obj['parentMovementRequired'] = ApiClient.convertToType(data['parentMovementRequired'], 'Boolean');
      }
      if (data.hasOwnProperty('sourceRepository')) {
        obj['sourceRepository'] = RepositoryDto.constructFromObject(data['sourceRepository']);
      }
      if (data.hasOwnProperty('targetRepository')) {
        obj['targetRepository'] = RepositoryDto.constructFromObject(data['targetRepository']);
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/MovementDto>} movements
   */
  exports.prototype['movements'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} parentMovementRequired
   */
  exports.prototype['parentMovementRequired'] = undefined;
  /**
   * @member {module:model/RepositoryDto} sourceRepository
   */
  exports.prototype['sourceRepository'] = undefined;
  /**
   * @member {module:model/RepositoryDto} targetRepository
   */
  exports.prototype['targetRepository'] = undefined;
  /**
   * @member {Date} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;



  return exports;
}));


