/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerDto', 'model/MovementDetailDto', 'model/MovementDto', 'model/MovementTypeDto', 'model/SupplierDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomerDto'), require('./MovementDetailDto'), require('./MovementDto'), require('./MovementTypeDto'), require('./SupplierDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.MovementDto = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.CustomerDto, root.InventoryManagementSystem.MovementDetailDto, root.InventoryManagementSystem.MovementDto, root.InventoryManagementSystem.MovementTypeDto, root.InventoryManagementSystem.SupplierDto);
  }
}(this, function(ApiClient, CustomerDto, MovementDetailDto, MovementDto, MovementTypeDto, SupplierDto) {
  'use strict';




  /**
   * The MovementDto model module.
   * @module model/MovementDto
   * @version 2.0
   */

  /**
   * Constructs a new <code>MovementDto</code>.
   * @alias module:model/MovementDto
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>MovementDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovementDto} obj Optional instance to populate.
   * @return {module:model/MovementDto} The populated <code>MovementDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('childrenMovement')) {
        obj['childrenMovement'] = ApiClient.convertToType(data['childrenMovement'], [MovementDto]);
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('customer')) {
        obj['customer'] = CustomerDto.constructFromObject(data['customer']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('movement')) {
        obj['movement'] = MovementDto.constructFromObject(data['movement']);
      }
      if (data.hasOwnProperty('movementDate')) {
        obj['movementDate'] = ApiClient.convertToType(data['movementDate'], 'Date');
      }
      if (data.hasOwnProperty('movementDetails')) {
        obj['movementDetails'] = ApiClient.convertToType(data['movementDetails'], [MovementDetailDto]);
      }
      if (data.hasOwnProperty('movementType')) {
        obj['movementType'] = MovementTypeDto.constructFromObject(data['movementType']);
      }
      if (data.hasOwnProperty('supplier')) {
        obj['supplier'] = SupplierDto.constructFromObject(data['supplier']);
      }
      if (data.hasOwnProperty('totalValue')) {
        obj['totalValue'] = ApiClient.convertToType(data['totalValue'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'Number');
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/MovementDto>} childrenMovement
   */
  exports.prototype['childrenMovement'] = undefined;
  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {String} comments
   */
  exports.prototype['comments'] = undefined;
  /**
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {module:model/CustomerDto} customer
   */
  exports.prototype['customer'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/MovementDto} movement
   */
  exports.prototype['movement'] = undefined;
  /**
   * @member {Date} movementDate
   */
  exports.prototype['movementDate'] = undefined;
  /**
   * @member {Array.<module:model/MovementDetailDto>} movementDetails
   */
  exports.prototype['movementDetails'] = undefined;
  /**
   * @member {module:model/MovementTypeDto} movementType
   */
  exports.prototype['movementType'] = undefined;
  /**
   * @member {module:model/SupplierDto} supplier
   */
  exports.prototype['supplier'] = undefined;
  /**
   * @member {Number} totalValue
   */
  exports.prototype['totalValue'] = undefined;
  /**
   * @member {Number} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Date} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;



  return exports;
}));


