/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MovementTypeDto', 'model/ProductRepositoryDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MovementTypeDto'), require('./ProductRepositoryDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.RepositoryDto = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.MovementTypeDto, root.InventoryManagementSystem.ProductRepositoryDto);
  }
}(this, function(ApiClient, MovementTypeDto, ProductRepositoryDto) {
  'use strict';




  /**
   * The RepositoryDto model module.
   * @module model/RepositoryDto
   * @version 2.0
   */

  /**
   * Constructs a new <code>RepositoryDto</code>.
   * @alias module:model/RepositoryDto
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>RepositoryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RepositoryDto} obj Optional instance to populate.
   * @return {module:model/RepositoryDto} The populated <code>RepositoryDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('external')) {
        obj['external'] = ApiClient.convertToType(data['external'], 'Boolean');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('productRepositories')) {
        obj['productRepositories'] = ApiClient.convertToType(data['productRepositories'], [ProductRepositoryDto]);
      }
      if (data.hasOwnProperty('sourceMovementTypes')) {
        obj['sourceMovementTypes'] = ApiClient.convertToType(data['sourceMovementTypes'], [MovementTypeDto]);
      }
      if (data.hasOwnProperty('targetMovementTypes')) {
        obj['targetMovementTypes'] = ApiClient.convertToType(data['targetMovementTypes'], [MovementTypeDto]);
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Boolean} external
   */
  exports.prototype['external'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<module:model/ProductRepositoryDto>} productRepositories
   */
  exports.prototype['productRepositories'] = undefined;
  /**
   * @member {Array.<module:model/MovementTypeDto>} sourceMovementTypes
   */
  exports.prototype['sourceMovementTypes'] = undefined;
  /**
   * @member {Array.<module:model/MovementTypeDto>} targetMovementTypes
   */
  exports.prototype['targetMovementTypes'] = undefined;
  /**
   * @member {Date} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;



  return exports;
}));


