/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InventoryManagementSystem);
  }
}(this, function(expect, InventoryManagementSystem) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InventoryManagementSystem.MovementDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MovementDto', function() {
    it('should create an instance of MovementDto', function() {
      // uncomment below and update the code to test MovementDto
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be.a(InventoryManagementSystem.MovementDto);
    });

    it('should have the property childrenMovement (base name: "childrenMovement")', function() {
      // uncomment below and update the code to test the property childrenMovement
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property movement (base name: "movement")', function() {
      // uncomment below and update the code to test the property movement
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property movementDate (base name: "movementDate")', function() {
      // uncomment below and update the code to test the property movementDate
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property movementDetails (base name: "movementDetails")', function() {
      // uncomment below and update the code to test the property movementDetails
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property movementType (base name: "movementType")', function() {
      // uncomment below and update the code to test the property movementType
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property supplier (base name: "supplier")', function() {
      // uncomment below and update the code to test the property supplier
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property totalValue (base name: "totalValue")', function() {
      // uncomment below and update the code to test the property totalValue
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new InventoryManagementSystem.MovementDto();
      //expect(instance).to.be();
    });

  });

}));
