/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductDto } from './productDto';
import { SupplierDto } from './supplierDto';


export interface CategoryDto { 
    createdAt?: Date;
    description?: string;
    id?: number;
    name?: string;
    parentCategory?: CategoryDto;
    products?: Array<ProductDto>;
    subCategories?: Array<CategoryDto>;
    supplier?: SupplierDto;
    updatedAt?: Date;
}
