/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerDto } from './customerDto';
import { MovementDetailDto } from './movementDetailDto';
import { MovementTypeDto } from './movementTypeDto';
import { SupplierDto } from './supplierDto';


export interface MovementDto { 
    childrenMovement?: Array<MovementDto>;
    code?: string;
    comments?: string;
    createdAt?: Date;
    customer?: CustomerDto;
    id?: number;
    movement?: MovementDto;
    movementDate?: Date;
    movementDetails?: Array<MovementDetailDto>;
    movementType?: MovementTypeDto;
    supplier?: SupplierDto;
    totalValue?: number;
    type?: number;
    updatedAt?: Date;
}
