/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryDto } from './categoryDto';
import { MovementDetailDto } from './movementDetailDto';
import { ProductRepositoryDto } from './productRepositoryDto';
import { SupplierDto } from './supplierDto';


export interface ProductDto { 
    category?: CategoryDto;
    code?: string;
    createdAt?: Date;
    description?: string;
    id?: number;
    movementDetails?: Array<MovementDetailDto>;
    name?: string;
    photo?: string;
    productRepositories?: Array<ProductRepositoryDto>;
    supplier?: SupplierDto;
    unitType?: number;
    updatedAt?: Date;
}
