/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MovementDetailDto } from './movementDetailDto';
import { ProductDto } from './productDto';
import { RepositoryDto } from './repositoryDto';


export interface ProductRepositoryDto { 
    createdAt?: Date;
    currentQuantity?: number;
    id?: number;
    negativeMovements?: Array<MovementDetailDto>;
    positiveMovements?: Array<MovementDetailDto>;
    price?: number;
    product?: ProductDto;
    repository?: RepositoryDto;
    updatedAt?: Date;
}
