export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './movementController.service';
import { MovementControllerService } from './movementController.service';
export * from './movementDetailController.service';
import { MovementDetailControllerService } from './movementDetailController.service';
export * from './movementTypeController.service';
import { MovementTypeControllerService } from './movementTypeController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './productRepositoryController.service';
import { ProductRepositoryControllerService } from './productRepositoryController.service';
export * from './repositoryController.service';
import { RepositoryControllerService } from './repositoryController.service';
export * from './rootController.service';
import { RootControllerService } from './rootController.service';
export * from './supplierController.service';
import { SupplierControllerService } from './supplierController.service';
export const APIS = [CategoryControllerService, CustomerControllerService, MovementControllerService, MovementDetailControllerService, MovementTypeControllerService, ProductControllerService, ProductRepositoryControllerService, RepositoryControllerService, RootControllerService, SupplierControllerService];
