/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { MovementDetailDto } from '../model/movementDetailDto';
import { ResponseCanonicalListMovementDetailDto } from '../model/responseCanonicalListMovementDetailDto';
import { ResponseCanonicalMovementDetailDto } from '../model/responseCanonicalMovementDetailDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MovementDetailControllerService {

    protected basePath = 'https://localhost:9091';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createMovementDetail
     * 
     * @param entityParam entityParam
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createMovementDetailUsingPOST(entityParam: MovementDetailDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseCanonicalMovementDetailDto>;
    public createMovementDetailUsingPOST(entityParam: MovementDetailDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseCanonicalMovementDetailDto>>;
    public createMovementDetailUsingPOST(entityParam: MovementDetailDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseCanonicalMovementDetailDto>>;
    public createMovementDetailUsingPOST(entityParam: MovementDetailDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (entityParam === null || entityParam === undefined) {
            throw new Error('Required parameter entityParam was null or undefined when calling createMovementDetailUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseCanonicalMovementDetailDto>(`${this.basePath}/movement-details/`,
            entityParam,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findMovementDetail
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findMovementDetailUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseCanonicalMovementDetailDto>;
    public findMovementDetailUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseCanonicalMovementDetailDto>>;
    public findMovementDetailUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseCanonicalMovementDetailDto>>;
    public findMovementDetailUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findMovementDetailUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ResponseCanonicalMovementDetailDto>(`${this.basePath}/movement-details/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listMovementDetails
     * 
     * @param productIds 
     * @param skip 
     * @param limit 
     * @param from 
     * @param to 
     * @param movementId 
     * @param omitPositive 
     * @param omitNegative 
     * @param sourceRepositoryId 
     * @param targetRepositoryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listMovementDetailsUsingGET(productIds?: Array<number>, skip?: number, limit?: number, from?: Date, to?: Date, movementId?: number, omitPositive?: boolean, omitNegative?: boolean, sourceRepositoryId?: number, targetRepositoryId?: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseCanonicalListMovementDetailDto>;
    public listMovementDetailsUsingGET(productIds?: Array<number>, skip?: number, limit?: number, from?: Date, to?: Date, movementId?: number, omitPositive?: boolean, omitNegative?: boolean, sourceRepositoryId?: number, targetRepositoryId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseCanonicalListMovementDetailDto>>;
    public listMovementDetailsUsingGET(productIds?: Array<number>, skip?: number, limit?: number, from?: Date, to?: Date, movementId?: number, omitPositive?: boolean, omitNegative?: boolean, sourceRepositoryId?: number, targetRepositoryId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseCanonicalListMovementDetailDto>>;
    public listMovementDetailsUsingGET(productIds?: Array<number>, skip?: number, limit?: number, from?: Date, to?: Date, movementId?: number, omitPositive?: boolean, omitNegative?: boolean, sourceRepositoryId?: number, targetRepositoryId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {











        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (productIds) {
            productIds.forEach((element) => {
                queryParameters = queryParameters.append('productIds', <any>element);
            })
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('skip', <any>skip);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (from !== undefined && from !== null) {
            queryParameters = queryParameters.set('from', <any>from.toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters = queryParameters.set('to', <any>to.toISOString());
        }
        if (movementId !== undefined && movementId !== null) {
            queryParameters = queryParameters.set('movementId', <any>movementId);
        }
        if (omitPositive !== undefined && omitPositive !== null) {
            queryParameters = queryParameters.set('omitPositive', <any>omitPositive);
        }
        if (omitNegative !== undefined && omitNegative !== null) {
            queryParameters = queryParameters.set('omitNegative', <any>omitNegative);
        }
        if (sourceRepositoryId !== undefined && sourceRepositoryId !== null) {
            queryParameters = queryParameters.set('sourceRepositoryId', <any>sourceRepositoryId);
        }
        if (targetRepositoryId !== undefined && targetRepositoryId !== null) {
            queryParameters = queryParameters.set('targetRepositoryId', <any>targetRepositoryId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ResponseCanonicalListMovementDetailDto>(`${this.basePath}/movement-details/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateMovementDetail
     * 
     * @param id id
     * @param entityParam entityParam
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateMovementDetailUsingPUT(id: number, entityParam: MovementDetailDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseCanonicalMovementDetailDto>;
    public updateMovementDetailUsingPUT(id: number, entityParam: MovementDetailDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseCanonicalMovementDetailDto>>;
    public updateMovementDetailUsingPUT(id: number, entityParam: MovementDetailDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseCanonicalMovementDetailDto>>;
    public updateMovementDetailUsingPUT(id: number, entityParam: MovementDetailDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateMovementDetailUsingPUT.');
        }

        if (entityParam === null || entityParam === undefined) {
            throw new Error('Required parameter entityParam was null or undefined when calling updateMovementDetailUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ResponseCanonicalMovementDetailDto>(`${this.basePath}/movement-details/${encodeURIComponent(String(id))}`,
            entityParam,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
