/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerDto', 'model/ResponseCanonicalCustomerDto', 'model/ResponseCanonicalListCustomerDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CustomerDto'), require('../model/ResponseCanonicalCustomerDto'), require('../model/ResponseCanonicalListCustomerDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.CustomerControllerApi = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.CustomerDto, root.InventoryManagementSystem.ResponseCanonicalCustomerDto, root.InventoryManagementSystem.ResponseCanonicalListCustomerDto);
  }
}(this, function(ApiClient, CustomerDto, ResponseCanonicalCustomerDto, ResponseCanonicalListCustomerDto) {
  'use strict';

  /**
   * CustomerController service.
   * @module api/CustomerControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new CustomerControllerApi. 
   * @alias module:api/CustomerControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createCustomerUsingPOST operation.
     * @callback module:api/CustomerControllerApi~createCustomerUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalCustomerDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createCustomer
     * @param {module:model/CustomerDto} entityParam entityParam
     * @param {module:api/CustomerControllerApi~createCustomerUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalCustomerDto}
     */
    this.createCustomerUsingPOST = function(entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling createCustomerUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalCustomerDto;

      return this.apiClient.callApi(
        '/customers/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findCustomerUsingGET operation.
     * @callback module:api/CustomerControllerApi~findCustomerUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalCustomerDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findCustomer
     * @param {Number} id id
     * @param {module:api/CustomerControllerApi~findCustomerUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalCustomerDto}
     */
    this.findCustomerUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findCustomerUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalCustomerDto;

      return this.apiClient.callApi(
        '/customers/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listCustomersUsingGET operation.
     * @callback module:api/CustomerControllerApi~listCustomersUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalListCustomerDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * listCustomers
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip 
     * @param {Number} opts.limit 
     * @param {Date} opts.from 
     * @param {Date} opts.to 
     * @param {String} opts.name 
     * @param {Number} opts.movementId 
     * @param {Number} opts.productId 
     * @param {module:api/CustomerControllerApi~listCustomersUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalListCustomerDto}
     */
    this.listCustomersUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'from': opts['from'],
        'to': opts['to'],
        'name': opts['name'],
        'movementId': opts['movementId'],
        'productId': opts['productId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalListCustomerDto;

      return this.apiClient.callApi(
        '/customers/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCustomerUsingPUT operation.
     * @callback module:api/CustomerControllerApi~updateCustomerUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalCustomerDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateCustomer
     * @param {Number} id id
     * @param {module:model/CustomerDto} entityParam entityParam
     * @param {module:api/CustomerControllerApi~updateCustomerUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalCustomerDto}
     */
    this.updateCustomerUsingPUT = function(id, entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateCustomerUsingPUT");
      }

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling updateCustomerUsingPUT");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalCustomerDto;

      return this.apiClient.callApi(
        '/customers/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
