/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MovementTypeDto', 'model/ResponseCanonicalListMovementTypeDto', 'model/ResponseCanonicalMovementTypeDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MovementTypeDto'), require('../model/ResponseCanonicalListMovementTypeDto'), require('../model/ResponseCanonicalMovementTypeDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.MovementTypeControllerApi = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.MovementTypeDto, root.InventoryManagementSystem.ResponseCanonicalListMovementTypeDto, root.InventoryManagementSystem.ResponseCanonicalMovementTypeDto);
  }
}(this, function(ApiClient, MovementTypeDto, ResponseCanonicalListMovementTypeDto, ResponseCanonicalMovementTypeDto) {
  'use strict';

  /**
   * MovementTypeController service.
   * @module api/MovementTypeControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new MovementTypeControllerApi. 
   * @alias module:api/MovementTypeControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createMovementTypeUsingPOST operation.
     * @callback module:api/MovementTypeControllerApi~createMovementTypeUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalMovementTypeDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createMovementType
     * @param {module:model/MovementTypeDto} entityParam entityParam
     * @param {module:api/MovementTypeControllerApi~createMovementTypeUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalMovementTypeDto}
     */
    this.createMovementTypeUsingPOST = function(entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling createMovementTypeUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalMovementTypeDto;

      return this.apiClient.callApi(
        '/movement-types/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findMovementTypeUsingGET operation.
     * @callback module:api/MovementTypeControllerApi~findMovementTypeUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalMovementTypeDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findMovementType
     * @param {Number} id id
     * @param {module:api/MovementTypeControllerApi~findMovementTypeUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalMovementTypeDto}
     */
    this.findMovementTypeUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findMovementTypeUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalMovementTypeDto;

      return this.apiClient.callApi(
        '/movement-types/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listMovementTypesUsingGET operation.
     * @callback module:api/MovementTypeControllerApi~listMovementTypesUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalListMovementTypeDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * listMovementTypes
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip 
     * @param {Number} opts.limit 
     * @param {Date} opts.from 
     * @param {Date} opts.to 
     * @param {String} opts.name 
     * @param {String} opts.description 
     * @param {Number} opts.sourceRepositoryId 
     * @param {Number} opts.targetRepositoryId 
     * @param {module:api/MovementTypeControllerApi~listMovementTypesUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalListMovementTypeDto}
     */
    this.listMovementTypesUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'from': opts['from'],
        'to': opts['to'],
        'name': opts['name'],
        'description': opts['description'],
        'sourceRepositoryId': opts['sourceRepositoryId'],
        'targetRepositoryId': opts['targetRepositoryId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalListMovementTypeDto;

      return this.apiClient.callApi(
        '/movement-types/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateMovementTypeUsingPUT operation.
     * @callback module:api/MovementTypeControllerApi~updateMovementTypeUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalMovementTypeDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateMovementType
     * @param {Number} id id
     * @param {module:model/MovementTypeDto} entityParam entityParam
     * @param {module:api/MovementTypeControllerApi~updateMovementTypeUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalMovementTypeDto}
     */
    this.updateMovementTypeUsingPUT = function(id, entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateMovementTypeUsingPUT");
      }

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling updateMovementTypeUsingPUT");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalMovementTypeDto;

      return this.apiClient.callApi(
        '/movement-types/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
