/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProductDto', 'model/ResponseCanonicalListProductDto', 'model/ResponseCanonicalProductDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ProductDto'), require('../model/ResponseCanonicalListProductDto'), require('../model/ResponseCanonicalProductDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.ProductControllerApi = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.ProductDto, root.InventoryManagementSystem.ResponseCanonicalListProductDto, root.InventoryManagementSystem.ResponseCanonicalProductDto);
  }
}(this, function(ApiClient, ProductDto, ResponseCanonicalListProductDto, ResponseCanonicalProductDto) {
  'use strict';

  /**
   * ProductController service.
   * @module api/ProductControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new ProductControllerApi. 
   * @alias module:api/ProductControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createProductUsingPOST operation.
     * @callback module:api/ProductControllerApi~createProductUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalProductDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createProduct
     * @param {module:model/ProductDto} entityParam entityParam
     * @param {module:api/ProductControllerApi~createProductUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalProductDto}
     */
    this.createProductUsingPOST = function(entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling createProductUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalProductDto;

      return this.apiClient.callApi(
        '/products/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findProductUsingGET operation.
     * @callback module:api/ProductControllerApi~findProductUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalProductDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findProduct
     * @param {Number} id id
     * @param {module:api/ProductControllerApi~findProductUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalProductDto}
     */
    this.findProductUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findProductUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalProductDto;

      return this.apiClient.callApi(
        '/products/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listProductsUsingGET operation.
     * @callback module:api/ProductControllerApi~listProductsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalListProductDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * listProducts
     * @param {Object} opts Optional parameters
     * @param {Array.<Number>} opts.sourceSupplierIds 
     * @param {Array.<Number>} opts.customerIds 
     * @param {Array.<Number>} opts.supplierIds 
     * @param {Array.<Number>} opts.categoryIds 
     * @param {Number} opts.skip 
     * @param {Number} opts.limit 
     * @param {Date} opts.from 
     * @param {Date} opts.to 
     * @param {String} opts.name 
     * @param {String} opts.description 
     * @param {module:api/ProductControllerApi~listProductsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalListProductDto}
     */
    this.listProductsUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'from': opts['from'],
        'to': opts['to'],
        'name': opts['name'],
        'description': opts['description'],
      };
      var collectionQueryParams = {
        'sourceSupplierIds': {
          value: opts['sourceSupplierIds'],
          collectionFormat: 'multi'
        },
        'customerIds': {
          value: opts['customerIds'],
          collectionFormat: 'multi'
        },
        'supplierIds': {
          value: opts['supplierIds'],
          collectionFormat: 'multi'
        },
        'categoryIds': {
          value: opts['categoryIds'],
          collectionFormat: 'multi'
        },
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalListProductDto;

      return this.apiClient.callApi(
        '/products/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateProductUsingPUT operation.
     * @callback module:api/ProductControllerApi~updateProductUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalProductDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateProduct
     * @param {Number} id id
     * @param {module:model/ProductDto} entityParam entityParam
     * @param {module:api/ProductControllerApi~updateProductUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalProductDto}
     */
    this.updateProductUsingPUT = function(id, entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateProductUsingPUT");
      }

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling updateProductUsingPUT");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalProductDto;

      return this.apiClient.callApi(
        '/products/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
