/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseCanonicalstring'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ResponseCanonicalstring'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.RootControllerApi = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.ResponseCanonicalstring);
  }
}(this, function(ApiClient, ResponseCanonicalstring) {
  'use strict';

  /**
   * RootController service.
   * @module api/RootControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new RootControllerApi. 
   * @alias module:api/RootControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the heartBeatUsingGET operation.
     * @callback module:api/RootControllerApi~heartBeatUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalstring} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * heartBeat
     * @param {module:api/RootControllerApi~heartBeatUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalstring}
     */
    this.heartBeatUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ResponseCanonicalstring;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
