/**
 * Inventory Management System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseCanonicalListSupplierDto', 'model/ResponseCanonicalSupplierDto', 'model/SupplierDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ResponseCanonicalListSupplierDto'), require('../model/ResponseCanonicalSupplierDto'), require('../model/SupplierDto'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryManagementSystem) {
      root.InventoryManagementSystem = {};
    }
    root.InventoryManagementSystem.SupplierControllerApi = factory(root.InventoryManagementSystem.ApiClient, root.InventoryManagementSystem.ResponseCanonicalListSupplierDto, root.InventoryManagementSystem.ResponseCanonicalSupplierDto, root.InventoryManagementSystem.SupplierDto);
  }
}(this, function(ApiClient, ResponseCanonicalListSupplierDto, ResponseCanonicalSupplierDto, SupplierDto) {
  'use strict';

  /**
   * SupplierController service.
   * @module api/SupplierControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new SupplierControllerApi. 
   * @alias module:api/SupplierControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createSupplierUsingPOST operation.
     * @callback module:api/SupplierControllerApi~createSupplierUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalSupplierDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createSupplier
     * @param {module:model/SupplierDto} entityParam entityParam
     * @param {module:api/SupplierControllerApi~createSupplierUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalSupplierDto}
     */
    this.createSupplierUsingPOST = function(entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling createSupplierUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalSupplierDto;

      return this.apiClient.callApi(
        '/suppliers/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findSupplierUsingGET operation.
     * @callback module:api/SupplierControllerApi~findSupplierUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalSupplierDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findSupplier
     * @param {Number} id id
     * @param {module:api/SupplierControllerApi~findSupplierUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalSupplierDto}
     */
    this.findSupplierUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findSupplierUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalSupplierDto;

      return this.apiClient.callApi(
        '/suppliers/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listSuppliersUsingGET operation.
     * @callback module:api/SupplierControllerApi~listSuppliersUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalListSupplierDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * listSuppliers
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip 
     * @param {Number} opts.limit 
     * @param {Date} opts.from 
     * @param {Date} opts.to 
     * @param {String} opts.name 
     * @param {Number} opts.movementId 
     * @param {Number} opts.productId 
     * @param {module:api/SupplierControllerApi~listSuppliersUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalListSupplierDto}
     */
    this.listSuppliersUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'from': opts['from'],
        'to': opts['to'],
        'name': opts['name'],
        'movementId': opts['movementId'],
        'productId': opts['productId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalListSupplierDto;

      return this.apiClient.callApi(
        '/suppliers/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSupplierUsingPUT operation.
     * @callback module:api/SupplierControllerApi~updateSupplierUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ResponseCanonicalSupplierDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateSupplier
     * @param {Number} id id
     * @param {module:model/SupplierDto} entityParam entityParam
     * @param {module:api/SupplierControllerApi~updateSupplierUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseCanonicalSupplierDto}
     */
    this.updateSupplierUsingPUT = function(id, entityParam, callback) {
      var postBody = entityParam;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateSupplierUsingPUT");
      }

      // verify the required parameter 'entityParam' is set
      if (entityParam === undefined || entityParam === null) {
        throw new Error("Missing the required parameter 'entityParam' when calling updateSupplierUsingPUT");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseCanonicalSupplierDto;

      return this.apiClient.callApi(
        '/suppliers/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
